name: Citra-libretro Linux x86_64

on:
  schedule:
    - cron: '0 2 * * *' # run at 2 AM UTC
  watch: # this is a hack that lets repo owners trigger a build by starring
    types: [started]
    if: github.actor == github.event.repository.owner.login

jobs:
  Windows:
    name: Build for Linux
    runs-on: ubuntu-latest

    steps:
    - name: Install needed packages
      run: sudo apt install wget git build-essential libbluetooth-dev libgl1-mesa-dev libxi-dev x11-utils libx11-dev libxext-dev libxrandr-dev libpthread-stubs0-dev
    - name: Get latest cmake
      uses: lukka/get-cmake@latest
    - name: Checkout source
      run: git clone https://github.com/libretro/citra.git && cd citra && git submodule update --init --recursive
    - name: Build libretro citra core
      working-directory: citra
      run: mkdir build && cd build && cmake -DENABLE_LIBRETRO=1 -DLIBRETRO_STATIC=1 -DENABLE_SDL2=0 -DENABLE_QT=0 -DCMAKE_BUILD_TYPE=Release -DENABLE_WEB_SERVICE=0 ..
    - name: Build the thing
      working-directory: citra/build
      run: cmake --build . --target citra_libretro
    - name: Prep for release
      working-directory: citra/build/src/citra_libretro
      run: |
        wget https://raw.githubusercontent.com/libretro/libretro-super/master/retrolink.sh && chmod +x retrolink.sh && ./retrolink.sh citra_libretro.so
        zip -9 ../../../../citra_libretro.so.zip citra_libretro.so
    - name: Create new release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        tag: Linux_64-bit
        file: citra_libretro.so.zip
        overwrite: true
