name: MelonDS-libretro Linux x86_64

on:
  schedule:
    - cron: '0 2 * * *' # run at 2 AM UTC
  watch: # this is a hack that lets repo owners trigger a build by starring
    types: [started]
    if: github.actor == github.event.repository.owner.login

jobs:
  Windows:
    name: Build for Linux
    runs-on: ubuntu-latest

    steps:
    - name: Install needed packages
      run: sudo apt install wget git build-essential libgl1-mesa-dev
    - name: Checkout source
      run: git clone https://github.com/libretro/melonds.git && cd melonds && git submodule update --init
    - name: Build libretro melonds core
      working-directory: melonds
      run: |
        make HAVE_THREADS=1 HAVE_OPENGL=1 JIT_ARCH=x64 -j8
        wget https://raw.githubusercontent.com/libretro/libretro-super/master/retrolink.sh && chmod +x retrolink.sh && ./retrolink.sh melonds_libretro.so
        zip -9 ../melonds_libretro.so.zip melonds_libretro.so
    - name: Create new release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        tag: Linux_64-bit
        file: melonds_libretro.so.zip
        overwrite: true
