name: scummvm libretro Linux aarch64

on:
  schedule:
    - cron: '0 2 * * *' # run at 2 AM UTC
  watch: # this is a hack that lets repo owners trigger a build by starring
    types: [started]
    if: github.actor == github.event.repository.owner.login

jobs:
  Linux:
    name: Build for Linux
    runs-on: ubuntu-latest

    steps:
    - name: Install needed packages
      run: sudo apt update && sudo apt install wget git build-essential
    - name: Checkout scummvm source
      run: git clone https://github.com/libretro/scummvm.git && cd scummvm && git submodule update --init
    - name: Checkout libretro backend source
      run: git clone https://github.com/diablodiab/libretro-scummvm-backend.git && mv libretro-scummvm-backend scummvm/backends/platform/libretro
    - name: Build libretro core
      working-directory: scummvm/backends/platform/libretro/build
      run: |
        make -j8
        wget https://raw.githubusercontent.com/libretro/libretro-super/master/retrolink.sh && chmod +x retrolink.sh && ./retrolink.sh scummvm_libretro.so
        zip -9 ../../../../../scummvm_libretro.so.zip scummvm_libretro.so
    - name: Create new release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        tag: Linux_64-bit
        file: scummvm_libretro.so.zip
        overwrite: true
