name: Mupen64plus-Next libretro Linux aarch64

on:
  schedule:
    - cron: '0 2 * * *' # run at 2 AM UTC
  watch: # this is a hack that lets repo owners trigger a build by starring
    types: [started]
    if: github.actor == github.event.repository.owner.login

jobs:
  Linux:
    name: Build for Linux
    runs-on: ubuntu-22.04-arm

    steps:
    - name: Install needed packages
      run: sudo apt update && sudo apt install wget git build-essential make libx11-dev libgles2-mesa-dev libegl-dev libxext-dev
    - name: Checkout source
      run: git clone https://github.com/libretro/mupen64plus-libretro-nx.git && cd mupen64plus-libretro-nx
    - name: Build libretro core
      working-directory: mupen64plus-libretro-nx
      run: |
        make -j8 GLES3=1
        wget https://raw.githubusercontent.com/libretro/libretro-super/master/retrolink.sh && chmod +x retrolink.sh && ./retrolink.sh mupen64plus_next_libretro.so
        zip -9 ../mupen64plus_next_libretro.so.zip mupen64plus_next_libretro.so
    - name: Create new release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        tag: Linux_aarch64
        file: mupen64plus_next_libretro.so.zip
        overwrite: true
