name: EasyRPG libretro Linux aarch64

on:
  schedule:
    - cron: '0 2 * * *' # run at 2 AM UTC
  watch: # this is a hack that lets repo owners trigger a build by starring
    types: [started]
    if: github.actor == github.event.repository.owner.login

jobs:
  Linux:
    name: Build for Linux
    runs-on: ubuntu-22.04-arm

    steps:
    - name: Install needed packages
      run: sudo apt update && sudo apt install wget git make automake pkg-config libtool build-essential libsdl2-dev libicu-dev libexpat1-dev libinih-dev
    - name: Checkout source
      run: git clone https://github.com/EasyRPG/Player.git && cd Player && git submodule update --init
    - name: Build libretro core
      working-directory: Player
      run: |
        mkdir build && cd build && cmake -DBUILD_SHARED_LIBS=ON -DPLAYER_TARGET_PLATFORM=libretro -DPLAYER_BUILD_LIBLCF=ON -DCMAKE_IGNORE_PATH=/usr/include -DCMAKE_BUILD_TYPE=Release" .. && cmake --build .
        wget https://raw.githubusercontent.com/libretro/libretro-super/master/retrolink.sh && chmod +x retrolink.sh && ./retrolink.sh easyrpg_libretro.so
        zip -9 ../../easyrpg_libretro.so.zip easyrpg_libretro.so
    - name: Create new release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        tag: Linux_aarch64
        file: easyrpg_libretro.so.zip
        overwrite: true
