name: scummvm libretro Linux aarch64

on:
  schedule:
    - cron: '0 2 * * *' # run at 2 AM UTC
  watch: # this is a hack that lets repo owners trigger a build by starring
    types: [started]
    if: github.actor == github.event.repository.owner.login

jobs:
  Linux:
    name: Build for Linux
    runs-on: ubuntu-22.04-arm

    steps:
    - name: Install needed packages
      run: sudo apt update && sudo apt install wget git build-essential make libx11-dev libxext-dev
    - name: Checkout source
      run: git clone https://github.com/scummvm/scummvm.git && cd scummvm && git submodule update --init
#    - name: include climits in a couple of files 
#      run: |
#        sed -i '1s;^;#include <climits>\n;' scummvm/engines/stark/console.cpp
#        sed -i '1s;^;#include <climits>\n;' scummvm/common/random.cpp
#        sed -i '1s;^;#include <climits>\n;' scummvm/base/commandLine.cpp
    - name: Build libretro core
      working-directory: scummvm/backends/platform/libretro
      run: |
        make -j8
        wget https://raw.githubusercontent.com/libretro/libretro-super/master/retrolink.sh && chmod +x retrolink.sh && ./retrolink.sh scummvm_libretro.so
        zip -9 ../../../../scummvm_libretro.so.zip scummvm_libretro.so
    - name: Create new release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        tag: Linux_aarch64
        file: scummvm_libretro.so.zip
        overwrite: true
