name: Swanstation libretro Linux aarch64

on:
  schedule:
    - cron: '0 2 * * *' # run at 2 AM UTC
  watch: # this is a hack that lets repo owners trigger a build by starring
    types: [started]
    if: github.actor == github.event.repository.owner.login

jobs:
  Linux:
    name: Build for Linux
    runs-on: ubuntu-22.04-arm

    steps:
    - name: Install needed packages
      run: sudo apt update && sudo apt install wget git build-essential cmake make libx11-dev libvulkan-dev libvulkan1 libgles2-mesa-dev libegl-dev libxext-dev
    - name: Checkout source
      run: git clone https://github.com/libretro/swanstation.git && cd swanstation && git submodule update --init
    - name: Build libretro core
      working-directory: swanstation
      run: |
        mkdir build && cd build && cmake .. -DUSE_EGL=ON -DCMAKE_SYSTEM_PROCESSOR=aarch64
        make -j8
        wget https://raw.githubusercontent.com/libretro/libretro-super/master/retrolink.sh && chmod +x retrolink.sh && ./retrolink.sh swanstation_libretro.so
        zip -9 ../../swanstation_libretro.so.zip swanstation_libretro.so
    - name: Create new release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        tag: Linux_aarch64
        file: swanstation_libretro.so.zip
        overwrite: true
