name: flycast libretro Linux aarch64

on:
  schedule:
    - cron: '0 2 * * *' # run at 2 AM UTC
  watch: # this is a hack that lets repo owners trigger a build by starring
    types: [started]
    if: github.actor == github.event.repository.owner.login

jobs:
  Linux:
    name: Build for Linux
    runs-on: ubuntu-22.04-arm

    steps:
    - name: Install needed packages
      run: sudo apt update && sudo apt install wget git build-essential make yasm libx11-dev libxext-dev libbluetooth-dev libusb-1.0-0-dev libgl1-mesa-dev libxi-dev x11-utils libxrandr-dev libpthread-stubs0-dev
    - name: Checkout source
      run: git clone https://github.com/flyinghead/flycast.git && cd flycast && git submodule update --init
    - name: prepare to build libretro flycast core
      working-directory: flycast
      run: mkdir build && cd build && cmake -DLIBRETRO=ON -DUSE_LIBCDIO=ON -DCMAKE_POSITION_INDEPENDENT_CODE=TRUE -DCMAKE_BUILD_TYPE=Release ..
    - name: Build the thing
      working-directory: flycast/build
      run: cmake --build . --target flycast_libretro --config Release

    - name: Prep for release
      working-directory: flycast/build
      run: |
        wget https://raw.githubusercontent.com/libretro/libretro-super/master/retrolink.sh && chmod +x retrolink.sh && ./retrolink.sh flycast_libretro.so
        zip -9 ../../flycast_libretro.so.zip flycast_libretro.so
    - name: Create new release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        tag: Linux_aarch64
        file: flycast_libretro.so.zip
        overwrite: true
