name: Genesis Plus GX Wide libretro Linux aarch64

on:
  schedule:
    - cron: '0 2 * * *' # run at 2 AM UTC
  watch: # this is a hack that lets repo owners trigger a build by starring
    types: [started]
    if: github.actor == github.event.repository.owner.login

jobs:
  Linux:
    name: Build for Linux
    runs-on: ubuntu-22.04-arm

    steps:
    - name: Install needed packages
      run: sudo apt update && sudo apt install wget git build-essential make libx11-dev libxext-dev
    - name: Checkout source
      run: git clone https://github.com/libretro/Genesis-Plus-GX-Wide.git && cd Genesis-Plus-GX-Wide && git submodule update --init
    - name: Build libretro core
      working-directory: Genesis-Plus-GX-Wide
      run: |
        make -f Makefile.libretro -j8
        wget https://raw.githubusercontent.com/libretro/libretro-super/master/retrolink.sh && chmod +x retrolink.sh && ./retrolink.sh genesis_plus_gx_wide_libretro.so
        zip -9 ../genesis_plus_gx_wide_libretro.so.zip genesis_plus_gx_wide_libretro.so
    - name: Create new release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        tag: Linux_aarch64
        file: genesis_plus_gx_wide_libretro.so.zip
        overwrite: true
