name: dolphin libretro Linux aarch64

on:
  schedule:
    - cron: '0 2 * * *' # run at 2 AM UTC
  watch: # this is a hack that lets repo owners trigger a build by starring
    types: [started]
    if: github.actor == github.event.repository.owner.login

jobs:
  Linux:
    name: Build for Linux
    runs-on: ubuntu-22.04-arm

    steps:
    - name: Install needed packages
      run: sudo apt update && sudo apt install wget git build-essential make yasm libx11-dev libxext-dev libbluetooth-dev libgl1-mesa-dev libxi-dev x11-utils libxrandr-dev libpthread-stubs0-dev
    - name: Checkout source
      run: git clone https://github.com/libretro/dolphin.git && cd dolphin && git submodule update --init
    - name: prepare to build libretro dolphin core
      working-directory: dolphin
      run: mkdir build && cd build && cmake -DLIBRETRO=ON -DENABLE_QT=0 -DCMAKE_BUILD_TYPE=Release -DCMAKE_VERBOSE_MAKEFILE=ON ..
    - name: Build the thing
      working-directory: dolphin/build
      run: cmake --build . --target dolphin_libretro --config Release

    - name: Prep for release
      working-directory: dolphin/build
      run: |
        wget https://raw.githubusercontent.com/libretro/libretro-super/master/retrolink.sh && chmod +x retrolink.sh && ./retrolink.sh dolphin_libretro.so
        zip -9 ../../dolphin_libretro.so.zip dolphin_libretro.so
    - name: Create new release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        tag: Linux_aarch64
        file: dolphin_libretro.so.zip
        overwrite: true
