name: LRPS2 libretro Windows x86_64

on:
  schedule:
    - cron: '0 2 * * *' # run at 2 AM UTC
  watch: # this is a hack that lets repo owners trigger a build by starring
    types: [started]
    if: github.actor == github.event.repository.owner.login

jobs:
  Windows:
    name: Build for Windows
    runs-on: windows-latest

    steps:
    - uses: ilammy/msvc-dev-cmd@v1.4.1
    - name: Checkout source
      run: git clone https://github.com/libretro/pcsx2.git && cd pcsx2 && git checkout libretro && git submodule update --init --recursive
    - name: compile the thing
      working-directory: pcsx2
      run: mkdir build && cd build && cmake .. -DLIBRETRO=ON -DCMAKE_BUILD_TYPE=Release -DCMAKE_LINK_WHAT_YOU_USE=TRUE && dir && msbuild ALL_BUILD.vcxproj
    - name: Prep for release
      working-directory: pcsx2\build\libretro\DEBUG
      run: Compress-Archive -CompressionLevel Optimal -Path pcsx2_libretro.dll -DestinationPath ..\..\..\..\pcsx2_libretro.dll.zip
    - name: Create new release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        tag: Windows_64-bit
        file: pcsx2_libretro.dll.zip
        overwrite: true
